import { Design } from '../ai/schemas';

export interface FileStructure {
    [path: string]: string;
}

/**
 * Generates a complete project file structure based on the system design.
 */
export function generateCode(design: Design): FileStructure {
    const files: FileStructure = {};
    const { techStack } = design;

    // 1. Root Configuration
    files['package.json'] = generatePackageJson(design);
    files['README.md'] = generateReadme(design);
    files['.gitignore'] = generateGitIgnore();
    files['docker-compose.yml'] = generateDockerCompose(design);

    // 2. Source Code
    // Basic structure
    files['src/index.ts'] = generateEntrypoint(design);

    // Database Configuration
    if (techStack?.database === 'PostgreSQL') {
        files['prisma/schema.prisma'] = generatePrismaSchema(design);
    }

    // API Routes
    if (design.api) {
        if (techStack?.frontend === 'Next.js' && !techStack.backend) {
            // Next.js API Routes (if no separate backend)
            // design.api.forEach(...)
        } else {
            // Express/Node routes
            files['src/routes.ts'] = generateExpressRoutes(design);
        }
    }

    return files;
}

function generatePackageJson(design: Design): string {
    const { techStack } = design;

    const deps: Record<string, string> = {
        "dotenv": "^16.0.0",
    };
    const devDeps: Record<string, string> = {
        "typescript": "^5.0.0",
        "@types/node": "^20.0.0",
        "ts-node": "^10.9.0",
        "nodemon": "^3.0.0"
    };

    // Add backend deps
    if (techStack?.backend === 'Node.js') {
        deps["express"] = "^4.18.0";
        deps["cors"] = "^2.8.5";
        devDeps["@types/express"] = "^4.17.0";
        devDeps["@types/cors"] = "^2.8.5";
    }

    // Add database deps
    if (techStack?.database === 'PostgreSQL') {
        deps["@prisma/client"] = "^5.0.0";
        devDeps["prisma"] = "^5.0.0";
    } else if (techStack?.database === 'MongoDB') {
        deps["mongoose"] = "^7.0.0";
    }

    return JSON.stringify({
        name: "generated-project",
        version: "1.0.0",
        description: "AI-generated boilerplate from ArchLab",
        main: "src/index.ts",
        scripts: {
            "start": "node dist/index.js",
            "dev": "nodemon src/index.ts",
            "build": "tsc"
        },
        dependencies: deps,
        devDependencies: devDeps
    }, null, 2);
}

function generateGitIgnore(): string {
    return `node_modules
dist
.env
.DS_Store
coverage
`;
}

function generateReadme(design: Design): string {
    return `# ${design.architecture.pattern} System

Generated by ArchLab AI.

## Architecture
${design.architecture.pattern} pattern selected.

### Tech Stack
- Frontend: ${design.techStack?.frontend || 'Not specified'}
- Backend: ${design.techStack?.backend || 'Not specified'}
- Database: ${design.techStack?.database || 'Not specified'}

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start database (Docker):
   \`\`\`bash
   docker-compose up -d
   \`\`\`

3. Run development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Components
${design.components.map(c => `- **${c.name}**: ${c.responsibilities.join(', ')}`).join('\n')}
`;
}

function generateDockerCompose(design: Design): string {
    const services: Record<string, any> = {};

    if (design.techStack?.database === 'PostgreSQL') {
        services['postgres'] = {
            image: 'postgres:15',
            environment: {
                POSTGRES_USER: 'admin',
                POSTGRES_PASSWORD: 'password',
                POSTGRES_DB: 'app_db'
            },
            ports: ['5432:5432'],
            volumes: ['postgres_data:/var/lib/postgresql/data']
        };
    } else if (design.techStack?.database === 'MongoDB') {
        services['mongo'] = {
            image: 'mongo:6',
            ports: ['27017:27017'],
            volumes: ['mongo_data:/data/db']
        };
    }

    if (design.techStack?.database === 'Redis' || design.components.some(c => c.name.toLowerCase().includes('cache'))) {
        services['redis'] = {
            image: 'redis:alpine',
            ports: ['6379:6379']
        };
    }

    return `version: '3.8'
services:
${Object.entries(services).map(([name, config]) => {
        return `  ${name}:
    image: ${config.image}
    ${config.environment ? `environment:
${Object.entries(config.environment).map(([k, v]) => `      ${k}: ${v}`).join('\n')}` : ''}
    ports:
${config.ports.map((p: string) => `      - "${p}"`).join('\n')}
    ${config.volumes ? `volumes:
${config.volumes.map((v: string) => `      - ${v}`).join('\n')}` : ''}`;
    }).join('\n\n')}

volumes:
  postgres_data:
  mongo_data:
`;
}

function generatePrismaSchema(design: Design): string {
    let schema = `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
`;

    if (!design.dataModel) return schema;

    design.dataModel.forEach(model => {
        schema += `\nmodel ${model.entity.replace(/\s+/g, '')} {\n`;
        schema += `  id    String @id @default(uuid())\n`;
        schema += `  createdAt DateTime @default(now())\n`;
        schema += `  updatedAt DateTime @updatedAt\n`;

        model.fields.forEach(field => {
            // Basic type mapping
            let type = 'String';
            const lowerType = field.type.toLowerCase();
            if (lowerType.includes('int')) type = 'Int';
            else if (lowerType.includes('bool')) type = 'Boolean';
            else if (lowerType.includes('date')) type = 'DateTime';
            else if (lowerType.includes('float') || lowerType.includes('decimal')) type = 'Float';

            schema += `  ${field.name} ${type}\n`;
        });
        schema += `}\n`;
    });

    return schema;
}

function generateEntrypoint(design: Design): string {
    return `import express from 'express';
import cors from 'cors';
import { router } from './routes';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// API Routes
app.use('/api', router);

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: '${design.architecture.pattern}' });
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});
`;
}

function generateExpressRoutes(design: Design): string {
    let code = `import { Router } from 'express';\n\nexport const router = Router();\n\n`;

    design.api?.forEach(endpoint => {
        const method = endpoint.method.toLowerCase(); // get, post, etc
        if (['get', 'post', 'put', 'delete', 'patch'].includes(method)) {
            code += `// ${endpoint.purpose}\n`;
            code += `router.${method}('${endpoint.path}', (req, res) => {\n`;
            code += `  res.json({ message: '${endpoint.purpose} implemented' });\n`;
            code += `});\n\n`;
        }
    });

    return code;
}
