import { Design } from './api';

export function generateMarkdown(design: Design, projectName: string = 'System Design'): string {
    const { requirements, architecture, components, dataModel, api } = design;
    const date = new Date().toLocaleDateString();

    return `# ${projectName} - API Architecture Document
Date: ${date}

## 1. System Overview

### Architecture Pattern
**${architecture.pattern}**

### Rationale
${architecture.rationale.map(r => `- ${r}`).join('\n')}

### Risks & Mitigations
${architecture.risks.map(r => `- ${r}`).join('\n')}

---

## 2. Requirements

### Actors
${requirements.actors.map(a => `- ${a}`).join('\n')}

### Functional Requirements
${requirements.functional.map(r => `- ${r}`).join('\n')}

### Non-Functional Requirements
${requirements.nfr.map(r => `- ${r}`).join('\n')}

### Assumptions
${requirements.assumptions.map(a => `- ${a}`).join('\n')}

---

## 3. Component Architecture

The system is composed of the following key components:

${components.map(c => `### ${c.name}
${c.responsibilities.map(r => `- ${r}`).join('\n')}
`).join('\n')}

---

## 4. Data Model

${dataModel.map(d => `### ${d.entity}
| Field | Type |
|-------|------|
${d.fields.map(f => `| ${f.name} | \`${f.type}\` |`).join('\n')}
`).join('\n')}

---

## 5. API Specification

${api.map(e => `### ${e.method} ${e.path}
**Purpose:** ${e.purpose}
`).join('\n')}

---

*Generated by ArchLab*
`;
}
